### ISSUE TITLE
Enhancement: Add option to skip license validation

### ISSUE THREAD

**Issue by Joerki** [CycloneDX/sbom-utility#106]
Hi guys,

I would like to use the sbom-utility tool to validate proper output (schema) of other SBOM tools that generate a CycloneDX SBOM.

I know that there are tools checking against JSON schemas, but all I found have dependencies to a certain runtime like Node.js, Java, Python, and I want a binary that can be simply integrated into a CI pipeline like sbom-utility.

It would be very helpful to have a switch (or another way like e.g. a licenses.json without entries)  so that license validation is skipped.

**Comment by mrutkows** [comment]
@Joerki apologies for taking so long to respond as my job changed in July.  I am trying to understand the problem and assume you mean on the `validation` command?  If so, the canonical schema from CycloneDX actually imports/uses the license (id) validation schema if that is the problem?   Also, there is a way to pass in a "custom" schema file where you could disable that import/check on license ID (using the canonical schema file as a start).  

If you could provide the command line example (and sample input file) that would allow me to sync. with your use case and better understand and not guess at the problem. Thanks!

**Comment by Joerki** [comment]
Dear Matt @mrutkows,
thanks for your response!
After looking deeper into the original JSON schema files of the CycloneDX format and the 3rd-party database I use (aboutcode-org/scancode-licensedb) I recognized that the database specifies IDs ("SPDX license keys") that are not present in the SPDX license list. I could not find an exact definition of the field in the project, so maybe I misunderstood the purpose of it. 
So my conclusion is that I consider only official SPDX IDs in my SBOMs, and the tool should not complain about it.

**Comment by mrutkows** [comment]
@Joerki If we are talking "license policy" `license.json` file can be updated and passed to the utility.  Given that SPDX IDs change quarterly, I seeded the list with the known set we encounter in my company which covers 2500 active software products.  

However, if we are speaking of pure "validation" errors, that is a list that the CDX spec. decided to take "in house" for both v1.5 and 1.6 spec. versions and can be found here:

https://github.com/CycloneDX/specification/blob/master/schema/spdx.schema.json

You can submit changes to this if it does indeed reflect changes (or errors) representing the current state of the actual SPDX ID list. 

Please know it is not uncommon for scanning tools to misuse the license ID field and put whatever IDs they encounter (instead of using the "name" field which is correct for licenses that are not recognized by the actual SPDX community).

Hope this helps!
