### ISSUE TITLE
Remote loading of Schema file from URL

### ISSUE THREAD

**Issue by trivediravi13** [CycloneDX/sbom-utility#109]
It would be really great if this TODO feature of remote schema loading can be implemented as soon as possible.

**Comment by mrutkows** [comment]
@trivediravi13 I have thought about this for some time (since creating the tool), but had deferred to wanting to make sure that people would be able to use it in isolated CI/CD systems.  However, understanding limitations of open source libraries  (and support for versions past draft 6) that I use to perform validation, limitations of JSON schema itself or the need to "just get it to work" it seems time to enable such a feature.

Let me see if I can expose a new command line flag to allow a URL to be passed to an external schema file and then put safeguards around it to assure it is reasonably a schema file that is intended to be applied to BOMs...

**Comment by mrutkows** [comment]
@trivediravi13 also, if you have a schema file in mind and the use case you can share; that would help me greatly in justifying and guiding my feature dev. as well as testing ;)
